pipeline {
    agent any

    environment {
        VENV = 'venv'
    }

    stages {
        stage('Clone repository') {
            steps {
                git branch: 'main', credentialsId: 'github-creds', url: 'https://github.com/BrahimChatri/alx-backend-python.git'
            }
        }

        stage('Check Git Branch') {
            steps {
                sh 'git branch'
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                . venv/bin/activate
                cd messaging_app
                pytest --junitxml=test-results.xml
                '''
            }
        }

        stage('Publish test report') {
            steps {
                junit 'messaging_app/test-results.xml'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}
