pipeline {
    agent any

    environment {
        VENV = 'venv'
        IMAGE_NAME = 'image/messaging_app'  
    }

    stages {
        stage('Clone repository') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/BrahimChatri/alx-backend-python.git'
            }
        }

        stage('Install dependencies and test') {
            steps {
                withPythonEnv("$VENV") {
                    sh '''
                    cd messaging_app
                    pip install -r requirements.txt
                    pytest --junitxml=test-results.xml
                    '''
                }
            }
        }

        stage('Publish test report') {
            steps {
                junit 'messaging_app/test-results.xml'
            }
        }

        stage('Build Docker image') {
            steps {
                sh '''
                cd messaging_app
                docker build -t $IMAGE_NAME .
                '''
            }
        }

        stage('Push Docker image to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker push $IMAGE_NAME
                    '''
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}
